services:
  postgres:
    image: postgres:16-alpine
    container_name: telekom-postgres
    environment:
      POSTGRES_DB: telekom_db
      POSTGRES_USER: telekom_user
      POSTGRES_PASSWORD: telekom_pass
    ports:
      - "5432:5432"
    volumes:
      - telekom-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U telekom_user -d telekom_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  telekom-pgdata: