spring:
  application:
    name: telekom

  datasource:
    url: jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
    username: postgres.itwdtfqafjqgmqaflrli
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 20000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          statement_batch_size: 0
          batch_size: 50
          order_inserts: true
          order_updates: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

app:
  admin:
    email: admin@example.com
    password: "PiaAdmin2026!"
    full-name: "Sistem Yöneticisi"

